"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['myapp.py']
APP_NAME = 'inorganiclikes'
DATA_FILES = ['chromedriver']
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'saru.icns',
    'packages': ['selenium'],
    'strip': True,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "InorganicLikes instagram automation tool 1.0",
        'CFBundleIdentifier': "jp.ddo.fujoker.InorganicLikes",
        'CFBundleVersion': "1.0",
        'CFBundleShortVersionString': "1.0",
        'NSHumanReadableCopyright': "Copyright (C) 2019, fujoker, All Rights Reserved"
        }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
